sudo: required
language: rust
dist: xenial

rust:
  - 1.31.0

env:
  global:
    - RUST_BACKTRACE=1

cache: 
  - cargo
  - pip

before_install:
  - sudo apt-get -y install python3-dev python3-pip python3-setuptools python3-wheel libopenmpi-dev python3-virtualenv
  - sudo pip3 install -U --upgrade pip

before_script:
  - rustup component add rustfmt-preview

script: ./check.sh
