language: rust

rust:
- 1.28.0

addons:
apt:
  packages:
    - libasound2-dev
    - libudev-dev
    - libssl-dev

env:
  global:
    - PKG_CONFIG_PATH=$HOME/prefix/lib/pkgconfig
    - RUST_BACKTRACE=1
    - AUDIODEV=null

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script: ./check.sh
