[package]
name = "human_play"
version = "0.1.0"
authors = ["John Foley <jfoley@cs.umass.edu>"]

[dependencies]
failure = "*"
clap = "*"
quicksilver = "0.2"
png = "*"

[dependencies.toybox]
version = "*"
path = "../toybox"

[dependencies.toybox-core]
version = "*"
path = "../core"