[package]
name = "human_play"
version = "0.1.0"
authors = ["John Foley <jfoley@cs.umass.edu>"]

[dependencies]
quicksliver = "0.2"
failure = "*"

[dependencies.toybox]
version = "*"
path = "../toybox"
