[package]
name = "space_invaders"
version = "0.1.0"
authors = ["John Foley <jfoley@cs.umass.edu>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
lazy_static = "*"
itertools = "*"
rand = "*"

[dependencies.toybox-core]
version = "*"
path = "../core"
