[package]
name = "ctoybox"
version = "0.1.0"
authors = ["Emma 'Frank' Tosch <etosch@cs.umass.edu>"]

[lib]
name = "ctoybox"
crate-type = ["cdylib"]

[dependencies.toybox]
version = "*"
path = "../toybox"

[dependencies]
failure = "0.1"
libc = "0.2"