[package]
name = "tb_pitfall"
version = "0.1.0"
authors = ["kclary <kclary@cs.umass.edu>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
lazy_static = "*"
rand  = "*"

[dependencies.toybox-core]
version = "*"
path = "../core"