[package]
name = "openai"
version = "0.1.0"
authors = ["Emma 'Frank' Tosch <etosch@cs.umass.edu>"]

[lib]
name = "openai"
crate-type = ["dylib"]

[dependencies.toybox]
version = "*"
path = "../toybox"

[dependencies]
failure = "*"