name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: apt install openmpi
      run: sudo apt-get install -y libopenmpi-dev
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.5
    - name: Install dependencies
      run: |
        pip install -U --upgrade pip
        pip install -U --only-binary=numpy -r REQUIREMENTS.txt
        pip install -r REQUIREMENTS.txt  
    - name: Install baselines
      working-directory: baselines
      run: python setup.py install 
    - name: Run "check.sh"
      run: ./check.sh
