name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: apt install openmpi
      run: sudo apt-get install -y libopenmpi-dev
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.5
    - name: Initialize virtual environment
      run: |
        python -m venv .env
        source .env/bin/activate
    - name: Install dependencies
      run: |
        pip install -U --upgrade pip
        pip install -U --only-binary=numpy -r REQUIREMENTS.txt  
    - name: Install baselines
      run: |
	cd baselines 
        python setup.py install 
    - name: Install Toybox
      run: |
        cd .. 
        python setup.py install
    - name: Run "check.sh"
      run: ./check.sh

    
