[package]
name = "gridworld"
version = "0.1.0"
authors = ["John Foley <jfoley@cs.umass.edu>"]

[dependencies]
serde = "*"
serde_json = "*"
serde_derive = "*"
lazy_static = "*"
rand = "0.6.3"
rand_core = "0.3.0"

[dependencies.toybox-core]
version = "*"
path = "../core"
